package org.jetbrains.qodana.engine.model

import java.nio.file.Path
import java.time.Duration

data class RuntimeContext(
    val ideDir: Path? = null,
    val timeout: Duration = Duration.ofMinutes(60),
    val timeoutExitCode: Int = 1,
    val envVars: Map<String, String> = emptyMap(),
    val properties: Map<String, String> = emptyMap(),
    val propertyFlags: List<String> = emptyList(),
    val failThreshold: Int? = null,
    val disableStatistics: Boolean = false,
    val noStatistics: Boolean = false,
    val forceFullHistory: Boolean = false,
    val clearCache: Boolean = false,
    val analysisId: String? = null,
    val jvmDebugPort: Int? = null,
    val applyFixes: Boolean = false,
    val cleanup: Boolean = false,
    val fixesStrategy: String? = null,
    val bootstrap: String? = null,
    val disableSanity: Boolean = false,
    val runPromo: String? = null,
    val script: String = "default",
    val commit: String? = null,
    val diffStart: String? = null,
    val diffEnd: String? = null,
    val forceLocalChangesScript: Boolean = false,
    val reversePrAnalysis: Boolean = false,
    val onlyDirectory: String? = null,
    val coverageDir: Path? = null,
    val globalConfigDir: Path? = null,
    val globalConfigId: String? = null,
    val effectiveConfigDir: Path? = null,
    val customConfigName: String? = null,
    val showReportPort: Int? = null,
    val deprecatedPort: Int? = null,
    val clangCompileCommands: String? = null,
    val clangArgs: String? = null,
    val cdnetSolution: String? = null,
    val cdnetProject: String? = null,
    val cdnetConfiguration: String? = null,
    val cdnetPlatform: String? = null,
    val cdnetNoBuild: Boolean = false,
)
