plugins {
    id("org.graalvm.buildtools.native")
}

// NOTE: each consuming module must independently pin
//     java { toolchain { vendor.set(JvmVendorSpec.GRAAL_VM) } }
// (see qodana-cli/build.gradle.kts). The same pin can't live here because the
// `java { }` DSL accessor isn't available to precompiled-script plugins.

val quickBuildEnabled: Boolean =
    when (val raw = findProperty("quick")?.toString()?.lowercase()) {
        null, "false" -> false
        "true" -> true
        else -> error("Unrecognized value for -Pquick: '$raw'. Use 'true' or 'false'.")
    }

graalvmNative {
    toolchainDetection.set(true)

    metadataRepository {
        enabled.set(true)
    }

    agent {
        defaultMode.set("standard")
        // NOTE: the agent captures some test-infrastructure entries
        // (junit-platform.properties, org.junit.platform.* services, the test
        // classes themselves) that aren't needed in the production binary.
        // The stripTestEntriesFromMetadata task in qodana-cli/build.gradle.kts
        // finalizes metadataCopy and removes them automatically.
        // The plugin's `accessFilterFiles` knob was tried first but doesn't
        // filter the test-class entries on 0.10.6 against our setup.
        //
        // Capture from BOTH `test` (non-Docker reflection — Clikt, Jackson,
        // InitCommand's file IO, send via MockQDCloudHttpClient) AND
        // `parityTest` (Docker-tagged tests — docker-java DTOs). The two sets
        // are merged into the committed JSON via mergeWithExisting.
        metadataCopy {
            inputTaskNames.add("test")
            inputTaskNames.add("parityTest")
            outputDirectories.add("src/main/resources/META-INF/native-image/org.jetbrains.qodana/${project.name}")
            mergeWithExisting.set(true)
        }
    }

    binaries {
        named("main") {
            imageName.set(project.name)
            fallback.set(false)
            quickBuild.set(quickBuildEnabled)
            // The version baked into the binary comes from BuildInfo.VERSION
            // (generated by the consuming module's build script) — see
            // QodanaCommand.VERSION's fallback chain. QodanaCommand.VERSION also
            // honours -Dqodana.version at runtime, which is useful for local
            // overrides via `qodana -Dqodana.version=X --version` but is not the
            // load-bearing mechanism for the shipped binary.
            buildArgs.add("-H:+ReportExceptionStackTraces")
            // Add `--initialize-at-run-time=<class-or-package>` entries here when
            // nativeCompile fails on build-time-initialization for a specific class.
        }
    }
}
