import internal.BundleWindowsCrt

plugins {
    id("org.graalvm.buildtools.native")
}

// NOTE: each consuming module must independently pin
//     java { toolchain { vendor.set(JvmVendorSpec.GRAAL_VM) } }
// (see qodana-cli/build.gradle.kts). The same pin can't live here because the
// `java { }` DSL accessor isn't available to precompiled-script plugins.

val quickBuildEnabled: Boolean =
    when (val raw = findProperty("quick")?.toString()?.lowercase()) {
        null, "false" -> false
        "true" -> true
        else -> error("Unrecognized value for -Pquick: '$raw'. Use 'true' or 'false'.")
    }

graalvmNative {
    toolchainDetection.set(true)

    metadataRepository {
        enabled.set(true)
    }

    agent {
        defaultMode.set("standard")
        // NOTE: the agent captures some test-infrastructure entries
        // (junit-platform.properties, org.junit.platform.* services, the test
        // classes themselves) that aren't needed in the production binary.
        // CONTRIBUTING.md documents the manual strip after each regeneration.
        // The plugin's `accessFilterFiles` knob was tried first but doesn't
        // filter the test-class entries on 0.10.6 against our setup.
        metadataCopy {
            inputTaskNames.add("test")
            outputDirectories.add("src/main/resources/META-INF/native-image/org.jetbrains.qodana/${project.name}")
            mergeWithExisting.set(true)
        }
    }

    binaries {
        named("main") {
            imageName.set(project.name)
            fallback.set(false)
            quickBuild.set(quickBuildEnabled)
            // The version baked into the binary comes from BuildInfo.VERSION
            // (generated by the consuming module's build script) — see
            // QodanaCommand.VERSION's fallback chain. QodanaCommand.VERSION also
            // honours -Dqodana.version at runtime, which is useful for local
            // overrides via `qodana -Dqodana.version=X --version` but is not the
            // load-bearing mechanism for the shipped binary.
            buildArgs.add("-H:+ReportExceptionStackTraces")
            // Add `--initialize-at-run-time=<class-or-package>` entries here when
            // nativeCompile fails on build-time-initialization for a specific class.
        }
    }
}

// QD-14812: GraalVM 21 (and current master) hard-codes /MD on Windows, mirroring the JDK's own /MD
// build (OpenJDK make/autoconf/flags-cflags.m4:591). The produced .exe therefore imports
// VCRUNTIME140.dll + VCRUNTIME140_1.dll, which only ship with the Microsoft VC++ Redistributable for
// VS 2015–2022 — absent on Server Core, LTSC SKUs, and stripped Windows containers. App-local
// bundling is the only viable mitigation; static /MT is upstream-impossible (oracle/graal#1762,
// open since 2019).
//
// Registered on all hosts so qodana-release.gradle.kts can reference it unconditionally. The task
// only succeeds on Windows hosts — it fails loudly otherwise (no silent skip per CLAUDE.md).
tasks.register<BundleWindowsCrt>("bundleWindowsCrt") {
    group = "build"
    description = "Copy Microsoft Visual C++ runtime DLLs next to the GraalVM-built Windows binary (QD-14812)."
    dependsOn("nativeCompile")
    outputDir.set(layout.buildDirectory.dir("native/nativeCompile"))
}
